import '../styles/globals.css'
import {text} from '../styles/fonts.js'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={text.className}>
        <main className='w-screen overflow-hidden'>{children}</main>
      </body>
    </html>
  )
}
